### ISSUE TITLE
control several module

### ISSUE THREAD

**Issue by admiral-v1** [alixahedi/PCF8574-STM32#1]
Hi ,
I used this library and it was great
With what code can I control several modules with different addresses?

**Comment by alixahedi** [comment]
To control several PCF8574 modules with different addresses using the library you provided, you can create multiple PCF8574_HandleTypeDef structures, each corresponding to a different PCF8574 device on the I2C bus. Each module has a unique address determined by the state of its A0, A1, and A2 pins. You initialize each module with its corresponding address and then perform read/write operations.

Here's an example of how to control two PCF8574 modules with different addresses:

`#include "pcf8574.h"

// Create handles for two PCF8574 modules
PCF8574_HandleTypeDef pcf8574_1;
PCF8574_HandleTypeDef pcf8574_2;

int main(void) {
    // HAL initialization
    HAL_Init();
    
    // I2C handle (example, customize as needed)
    I2C_HandleTypeDef hi2c1;
    // Initialize your I2C peripheral (ensure this is done based on your project setup)
    // HAL_I2C_Init(&hi2c1);

    // Initialize the first PCF8574 (A0 = 0, A1 = 0, A2 = 0)
    PCF8574_Init(&pcf8574_1, &hi2c1, 0, 0, 0);

    // Initialize the second PCF8574 (A0 = 1, A1 = 0, A2 = 0)
    PCF8574_Init(&pcf8574_2, &hi2c1, 1, 0, 0);

    while (1) {
        // Toggle Pin 0 of the first PCF8574
        PCF8574_TogglePin(&pcf8574_1, 0);

        // Delay for 500 ms
        HAL_Delay(500);

        // Toggle Pin 0 of the second PCF8574
        PCF8574_TogglePin(&pcf8574_2, 0);

        // Delay for 500 ms
        HAL_Delay(500);
    }
}
`

**Comment by alixahedi** [comment]
To control several PCF8574 modules with different addresses using the library you provided, you can create multiple PCF8574_HandleTypeDef structures, each corresponding to a different PCF8574 device on the I2C bus. Each module has a unique address determined by the state of its A0, A1, and A2 pins. You initialize each module with its corresponding address and then perform read/write operations.

Here's an example of how to control two PCF8574 modules with different addresses:

```
#include "pcf8574.h"

// Create handles for two PCF8574 modules
PCF8574_HandleTypeDef pcf8574_1;
PCF8574_HandleTypeDef pcf8574_2;

int main(void) {
    // HAL initialization
    HAL_Init();
    
    // I2C handle (example, customize as needed)
    I2C_HandleTypeDef hi2c1;
    // Initialize your I2C peripheral (ensure this is done based on your project setup)
    // HAL_I2C_Init(&hi2c1);

    // Initialize the first PCF8574 (A0 = 0, A1 = 0, A2 = 0)
    PCF8574_Init(&pcf8574_1, &hi2c1, 0, 0, 0);

    // Initialize the second PCF8574 (A0 = 1, A1 = 0, A2 = 0)
    PCF8574_Init(&pcf8574_2, &hi2c1, 1, 0, 0);

    while (1) {
        // Toggle Pin 0 of the first PCF8574
        PCF8574_TogglePin(&pcf8574_1, 0);

        // Delay for 500 ms
        HAL_Delay(500);

        // Toggle Pin 0 of the second PCF8574
        PCF8574_TogglePin(&pcf8574_2, 0);

        // Delay for 500 ms
        HAL_Delay(500);
    }
}
```
